services:
  mongodb:
    image: mongo:8
    container_name: botv2_mongodb
    ports:
      - '127.0.0.1:27017:27017'
    networks:
      - default
    volumes:
      - type: volume
        source: v2mongo-db
        target: /data/db
      - type: volume
        source: v2mongo-configdb
        target: /data/configdb
    restart: unless-stopped
volumes:
  v2mongo-db:
    external: true
    name: botv2_mongodb-db
  v2mongo-configdb:
    external: true
    name: botv2_mongodb-configdb
networks:
  default:
    name: 'mobiv2-network'
